services:
  api:
    container_name: todoitems-api
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 1433:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["todoitems-api-sql"]
    networks:
      todoitems-networks:

  todoitems-api-sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=todolist2121"
    volumes:
      - "todoitems-api-sql:/var/opt/mssql"
    networks:
      todoitems-networks:
        aliases:
          - "sql"

volumes:
  todoitems-api-sql:

networks:
  todoitems-networks:
    driver: bridge


# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sqlserver
#     environment:
#       - SA_PASSWORD=todolist2121
#       - ACCEPT_EULA=Y
#     ports:
#       - "1433:1433"
#     volumes:
#       - sqlvolume:/var/opt/mssql

#   webapi:
#     build: .
#     ports:
#       - "8080:80"
#     depends_on:
#       - sqlserver

# volumes:
#   sqlvolume:
